apps/docmost/base/docmost-statefulset.yaml

Docmost fix pinned version

---

apps/docmost/base/docmost-statefulset.yaml

docmost fix

---

apps/docmost/prod/certificate.yaml
apps/docmost/prod/httpproxy.yaml
apps/planka/resources/certificate.yaml
apps/vaultwarden/helm/values.yaml
apps/vaultwarden/kustomization.yaml
apps/vaultwarden/resources/certificate.yaml
apps/vaultwarden/resources/httpproxy.yaml
apps/vaultwarden/vaultwarden.argoapp.yaml

vaultwarden

---

apps/vaultwarden/helm/values.yaml

increased tries

---

apps/vaultwarden/helm/values.yaml

removed replica

---

apps/kubero-ui/prod/httpproxy.yaml

fixed service name in ingress

---

apps/kubero-ui/base/kubero.yaml

no forced login, no admin panel

kubero fixes

---

apps/kubero-ui/base/kubero.yaml

typo dans kubero env

---

apps/kubero-ui/base/kubero.yaml

kubero env fix

---

apps/kubero-ui/base/kubero.yaml

kubero plz

---

apps/kubero-ui/base/kubero.yaml

kubero auth literal test

---

apps/kubero-ui/base/kubero.yaml

kubero typo

---

apps/kubero-ui/base/kubero.yaml

kubero fix auth callback url

---

apps/kubero-ui/base/kubero.yaml

kubero scope fix

---

apps/nextcloud/collabora-values.yaml
apps/nextcloud/nextcloud-setup.bash
data/clubs.yaml
data/nextcloud-external-sites.yaml

small fixes

---

apps/kubero-ui/base/kubero.yaml

metrics kubero

---

apps/nextcloud/nextcloud-setup.bash
apps/nextcloud/nextcloud-values.yaml

fix cron background tasks

---

apps/nextcloud/nextcloud-setup.bash

new excalidraw integration

---

apps/kubero-operator/base/rbac.yaml

kubero operator rbac namespaces fix

---

apps/kubero-operator/base/deployment.yaml

kubero operator version

---

apps/kubero-ui/base/kubero.yaml
apps/kubero-ui/kubero-ui.argoapp.yaml

kubero revert 2.4.6

---

apps/nextcloud/nextcloud-setup.bash
data/clubs.yaml

Ajouter le dossier pour conjure, 1Tb
et modification des roles de membres pour ne pas permettre delete

nextcloud ajout conjure & change role for members

---

apps/authentik/helm/values.yaml
apps/authentik/kustomization.yaml
apps/authentik/resources/pvc.yaml

Adding a pvc to authentik for branding. to have persistent logo and images.

authentik branding pvc

---

apps/authentik/helm/values.yaml
apps/authentik/resources/pvc.yaml

authentik pvc fix

---

apps/authentik/helm/values.yaml

authentik pvc

---

data/clubs.yaml

nextcloud ajout chinook

---

data/clubs.yaml

Nextcloud capra

---

apps/docmost/base/docmost-statefulset.yaml

fix docmost image fail

---

apps/docmost/base/docmost-statefulset.yaml

Should fix image failing to pull from docker rate limits

adds imagePullSecret to docmost

---

apps/docmost/base/redis-statefulset.yaml

Should fix redis image failing to pull from rate limits

adds imagePullSecret to docmost redis

---

apps/docmost/base/docmost-statefulset.yaml

Should fix docmost failing to start because of user permissions

bugfix docmost securityContext crashing app

---

apps/vaultwarden/base/deployment.yaml

Should fix vaultwarden unable to pull image from docker rate limits

adds imagePullSecret to vaultwarden
